import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/navbar/header.jsx";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={`${jost.className} h-full`}
    >
      
      <body className={`${jost.className} min-h-full flex flex-col `}>
        <Header />
        {children}
        </body>
    </html>
  );
}
